SELECT *
FROM Funcionario;

-- DISTINCT
SELECT DISTINCT F.Salario
FROM FUNCIONARIO AS F;

SELECT DISTINCT D.Dnome
FROM DEPARTAMENTO AS D;

-- WHERE
SELECT F.Pnome AS Nome, F.Salario, F.Cpf
FROM FUNCIONARIO AS F
WHERE Pnome LIKE '%joão'


-- ORDER BY
SELECT F.Pnome AS Nome, F.Salario*12 AS "Custo Anual"
FROM FUNCIONARIO AS F
ORDER BY Salario DESC;

-- NOT NULL
SELECT F.Pnome
FROM FUNCIONARIO AS F
WHERE Cpf_supervisor IS NOT NULL;

-- SELECT TOP
SELECT TOP 3 F.Pnome AS Nome, F.Salario 
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC;

-- MIN MAX
SELECT MIN(F.Salario) 
FROM FUNCIONARIO AS F;

-- SELECT ANINHADO
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = (SELECT MIN(F.Salario) 
				   FROM FUNCIONARIO AS F);

DECLARE @salario_min DECIMAL(10, 2);
SET @salario_min = (SELECT MIN(Salario) FROM FUNCIONARIO);

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = @salario_min

-- COUNT AVG SUM
SELECT F.Pnome AS Nome, F.Cpf, F.Salario
FROM FUNCIONARIO AS F 
WHERE F.Salario < (SELECT AVG(Salario)
				   FROM FUNCIONARIO)
ORDER BY F.Salario ASC;

-- LIKE
SELECT F.Pnome AS Nome, F.Cpf, F.Salario
FROM FUNCIONARIO AS F 
WHERE F.Datanasc LIKE '__72%';