-- EXCEPT
SELECT F.Cpf
FROM FUNCIONARIO AS F
EXCEPT 
SELECT D.Cpf_gerente
FROM DEPARTAMENTO AS D;

-- INTERSERCT
SELECT Cpf
FROM FUNCIONARIO 
INTERSECT
SELECT Cpf_supervisor
FROM FUNCIONARIO ;

-- GROUP BY
SELECT COUNT(F.Cpf) AS "Qtd", F.Sexo
FROM FUNCIONARIO AS F
GROUP BY F.Sexo;

SELECT COUNT(F.Cpf) AS "Qtd", D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
    ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT SUM(F.Salario) AS "Valor Total", D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
    ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT AVG(T.Horas) AS "Media Horas", P.Projnome
FROM TRABALHA_EM AS T
JOIN PROJETO AS P
    ON T.Pnr = P.Projnumero
GROUP BY P.Projnome

SELECT MAX(F.Salario) AS "Maior Salário", D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
    ON F.Dnr = D.Dnumero
GROUP BY D.Dnome 

-- EXISTS
SELECT * 
FROM DEPARTAMENTO
WHERE EXISTS (
    SELECT 1
    FROM PROJETO
    WHERE PROJETO.Dnum = DEPARTAMENTO.Dnumero
)

-- ALL / ANY (<> -> diferente)
SELECT Pnome, Salario
FROM FUNCIONARIO
WHERE Salario <> ALL (
    SELECT F.Salario
    FROM FUNCIONARIO AS F
    JOIN DEPARTAMENTO AS D
        ON F.Dnr = D.Dnumero
    WHERE D.Dnome = 'Administração'
    )
ORDER BY SALARIO;